kind = "web"
previewPath = "/"
title = "Jasa Tugas"
version = "1.0.0"
id = "artifacts/jasa-tugas"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24771

[services.development]
run = "pnpm --filter @workspace/jasa-tugas run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jasa-tugas", "run", "build" ]
publicDir = "artifacts/jasa-tugas/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24771"
BASE_PATH = "/"
